@startuml

start
:Passwort-Reset wird aufgerufen;

:Passwort einlesen;

if (Passwort-Modus?) then (weak)
    :Überprüfe R1;
    :Überprüfe R3;
else (strict)
    :Überprüfe R1;
    :Überprüfe R2;
    :Überprüfe R3;
    :Überprüfe R4;
endif

if (Alle Regeln erfüllt?) then (ja)
    :Passwort-Reset-Flow fortführen;
    stop
else (nein)
    :Fehlermeldung anzeigen;
    :Passwort-Reset abbrechen;
    end

endif

@enduml
